### ISSUE TITLE
missing placeholder file "ComfyUI/Styles/mystyle.csv"

### ISSUE THREAD

**Issue by LockMan007** [Feidorian/feidorian-ComfyNodes#1]
missing placeholder file "ComfyUI/Styles/mystyle.csv"

[feidorian-ComfyNodes] | WARNING -> Styles directory does not exist
[ERROR] An error occurred while retrieving information for the 'Feidorian_TextEncodedStyleLoader' node.
Traceback (most recent call last):
  File "\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
    out[x] = node_info(x)
  File "\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "\ComfyUI_windows_portable\ComfyUI\custom_nodes\feidorian-ComfyNodes\py\loaders\style_loader.py", line 72, in INPUT_TYPES
    load_CSV(cls)
  File "\ComfyUI_windows_portable\ComfyUI\custom_nodes\feidorian-ComfyNodes\py\loaders\style_loader.py", line 13, in load_CSV
    if not (files := [f for f in input_dir.iterdir() if f.suffix == ".csv"]):
  File "\ComfyUI_windows_portable\ComfyUI\custom_nodes\feidorian-ComfyNodes\py\loaders\style_loader.py", line 13, in <listcomp>
    if not (files := [f for f in input_dir.iterdir() if f.suffix == ".csv"]):
  File "pathlib.py", line 1017, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\ComfyUI_windows_portable\\ComfyUI\\styles'

**Comment by Feidorian** [comment]
@LockMan007 I apologize for the late the reply. I had no idea this project had gained traction. To fix the issue, you can just create the directory and place a csv file with the aforementioned name. I would provide an example style csv file if needed.
